'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.CodeDom.Compiler
Imports System.ComponentModel
Imports System.Globalization
Imports System.Resources
Imports System.Runtime.CompilerServices

Namespace My.Resources

    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), _
     DebuggerNonUserCode(), _
     CompilerGenerated(), _
     HideModuleName()> _
    Friend Module Resources

        Private resourceMan As ResourceManager

        Private resourceCulture As CultureInfo

        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <EditorBrowsable(EditorBrowsableState.Advanced)> _
        Friend ReadOnly Property ResourceManager() As ResourceManager
            Get
                If ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As ResourceManager = New ResourceManager("Heladeria_Tu_Gusto.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property

        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <EditorBrowsable(EditorBrowsableState.Advanced)> _
        Friend Property Culture() As CultureInfo
            Get
                Return resourceCulture
            End Get
            Set(value As CultureInfo)
                resourceCulture = value
            End Set
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ice_2377713_640() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ice-2377713_640", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ice_cream() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ice_cream", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_Add_128() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-Add-128", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_Add_New_40() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-Add New-40", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_Banana_split_80() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-Banana split-80", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_Delete_40() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-Delete-40", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_Edit_Property_128() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-Edit Property-128", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_Edit_Property_1281() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-Edit Property-1281", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_Ice_Cream_Sundae_80() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-Ice Cream Sundae-80", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_Package_128() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-Package-128", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_Resume_80() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-Resume-80", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property icons8_Save_as_64() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("icons8-Save as-64", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property popsicle_1267592_1280() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("popsicle-1267592_1280", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property

        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property supplier() As Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("supplier", resourceCulture)
                Return CType(obj, Bitmap)
            End Get
        End Property
    End Module
End Namespace
